// Auto-generated by Homepage Configurator.
// Emergency recovery draft reconstructed from index.html.
window.__CONFIGURATOR_DRAFT__ = {
	"brand": {
		"name": "VinATech",
		"logoSrc": "",
		"logoFileName": "",
		"logos": [
			{
				"src": "",
				"fileName": "",
				"x": 4,
				"y": 17,
				"size": 72,
				"rotation": 0,
				"transparency": 0
			},
			{
				"src": "",
				"fileName": "",
				"x": 92,
				"y": 12,
				"size": 72,
				"rotation": 0,
				"transparency": 0
			}
		]
	},
	"hero": {
		"title": "Android  Software, Digital Solutions",
		"subtitle": "Inspire. Win. Promote.",
		"titleFontFamily": "Sora",
		"subtitleFontFamily": "Manrope",
		"titleAlign": "left",
		"subtitleAlign": "center",
		"titleColor": "#f7fcfb",
		"subtitleColor": "#d1e0dc",
		"buttons": [
			{
				"label": "Solutions",
				"href": "solutions.html"
			},
			{
				"label": "Products",
				"href": "products.html"
			}
		]
	},
	"theme": {
		"fontFamily": "Sora",
		"headingSize": 79,
		"bodySize": 24,
		"buttonTextSize": 16,
		"bgColor": "#0f100f",
		"textColor": "#dbe6e6",
		"accentColor": "#6b9e97",
		"mutedColor": "#d3dedb",
		"surfaceColor": "#c2a8a8",
		"buttonTextColor": "#e0d1d1"
	},
	"background": {
		"src": "images/nv-photo.png",
		"fileName": "",
		"transparency": 0,
		"x": 50,
		"y": 50
	},
	"layout": {
		"logo": {
			"x": 0,
			"y": 0
		},
		"nav": {
			"x": 12,
			"y": -44
		},
		"hero": {
			"x": 0,
			"y": 0
		},
		"heroTitle": {
			"x": 248,
			"y": 22
		},
		"heroSubtitle": {
			"x": 163,
			"y": 6
		},
		"cta": {
			"x": 260,
			"y": -353
		}
	},
	"display": {
		"tabMode": "top-and-home",
		"topTabsTransparent": true,
		"ctaTextOnly": true
	},
	"tabs": [
		{
			"label": "Privacy",
			"sectionId": "privacy",
			"sectionTitle": "Privacy",
			"sectionText": "Add section content here.",
			"sectionFontFamily": "",
			"sectionTitleColor": "#102822",
			"sectionTextColor": "#4f6962",
			"sectionBackgroundColor": "#e5f0ea",
			"navFontFamily": "",
			"navTextColor": "#102822",
			"navBackgroundColor": "#39845b",
			"sectionBackgroundSrc": "",
			"sectionBackgroundFileName": "",
			"sectionBackgroundTransparency": 36,
			"galleryLayout": "horizontal",
			"galleryImageTransparency": 0,
			"galleryImages": [
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" }
			]
		},
		{
			"label": "About",
			"sectionId": "about",
			"sectionTitle": "About",
			"sectionText": "Add section content here.",
			"sectionFontFamily": "",
			"sectionTitleColor": "#102822",
			"sectionTextColor": "#4f6962",
			"sectionBackgroundColor": "#e5f0ea",
			"navFontFamily": "",
			"navTextColor": "#102822",
			"navBackgroundColor": "#c2a8a8",
			"sectionBackgroundSrc": "",
			"sectionBackgroundFileName": "",
			"sectionBackgroundTransparency": 36,
			"galleryLayout": "horizontal",
			"galleryImageTransparency": 0,
			"galleryImages": [
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" }
			]
		},
		{
			"label": "Test",
			"sectionId": "test",
			"sectionTitle": "Test",
			"sectionText": "Add section content here.",
			"sectionFontFamily": "",
			"sectionTitleColor": "#102822",
			"sectionTextColor": "#4f6962",
			"sectionBackgroundColor": "#e5f0ea",
			"navFontFamily": "",
			"navTextColor": "#102822",
			"navBackgroundColor": "#c2a8a8",
			"sectionBackgroundSrc": "",
			"sectionBackgroundFileName": "",
			"sectionBackgroundTransparency": 36,
			"galleryLayout": "horizontal",
			"galleryImageTransparency": 0,
			"galleryImages": [
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" },
				{ "src": "", "fileName": "" }
			]
		}
	]
};
