// Auto-generated by Homepage Configurator.
// Commit this file to keep draft settings synced across devices.
window.__CONFIGURATOR_DRAFT__ = {
  "brand": {
    "name": "VinATech",
    "logoSrc": "",
    "logoFileName": "",
    "logos": [
      {
        "src": "",
        "fileName": "",
        "x": 4,
        "y": 17,
        "size": 72,
        "rotation": 0,
        "transparency": 0
      },
      {
        "src": "",
        "fileName": "",
        "x": 92,
        "y": 12,
        "size": 72,
        "rotation": 0,
        "transparency": 0
      }
    ]
  },
  "hero": {
    "title": "Intelligence, Scale and Digital Solutions",
    "subtitle": "Inspire. Innovate. Ambition.",
    "titleFontFamily": "Sora",
    "subtitleFontFamily": "Manrope",
    "titleAlign": "center",
    "subtitleAlign": "center",
    "titleColor": "#f7fcfb",
    "subtitleColor": "#ebefee",
    "buttons": [
      {
        "label": "Solutions",
        "href": "solutions.html"
      },
      {
        "label": "Products",
        "href": "products.html"
      },
      {
        "label": "Support",
        "href": "support.html"
      },
      {
        "label": "Contact",
        "href": "contact.html"
      }
    ]
  },
  "theme": {
    "fontFamily": "Sora",
    "headingSize": 59,
    "bodySize": 20,
    "buttonTextSize": 16,
    "bgColor": "#011301",
    "textColor": "#dbe6e6",
    "accentColor": "#011313",
    "mutedColor": "#87a69e",
    "surfaceColor": "#9e5757",
    "buttonTextColor": "#e0d1d1",
    "mobileHeadingSize": 73,
    "mobileBodySize": 23
  },
  "background": {
    "src": "images/nv-photo.png",
    "fileName": "",
    "transparency": 0,
    "x": 0,
    "y": 17
  },
  "layout": {
    "logo": {
      "x": 0,
      "y": 0
    },
    "nav": {
      "x": 4,
      "y": -40
    },
    "hero": {
      "x": 0,
      "y": 0
    },
    "heroTitle": {
      "x": 229,
      "y": 27
    },
    "heroSubtitle": {
      "x": 234,
      "y": 19
    },
    "cta": {
      "x": 572,
      "y": -289
    },
    "mobileNav": {
      "x": 0,
      "y": 0
    },
    "mobileHeroTitle": {
      "x": 0,
      "y": 0
    },
    "mobileHeroSubtitle": {
      "x": 0,
      "y": 0
    },
    "mobileCta": {
      "x": 0,
      "y": 0
    }
  },
  "display": {
    "tabMode": "top-only",
    "topTabsTransparent": true,
    "ctaTextOnly": true,
    "previewDevice": "mobile",
    "mobileHeroCenter": true,
    "mobileOverrides": false
  },
  "tabs": [
    {
      "label": "HOME",
      "sectionId": "home",
      "pageHref": "index.html",
      "sectionTitle": "home",
      "sectionText": "Add content for this section before publishing.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#4c5757",
      "sectionTextColor": "#0b322a",
      "sectionBackgroundColor": "#605252",
      "navFontFamily": "Sora",
      "navTextColor": "#0d2b2b",
      "navBackgroundColor": "#9e5757",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    },
    {
      "label": "NEWS",
      "sectionId": "news",
      "pageHref": "news.html",
      "sectionTitle": "news",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#9e5757",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    },
    {
      "label": "PRIVACY POLICY",
      "sectionId": "privacy",
      "pageHref": "privacy.html",
      "sectionTitle": "Privacy",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#39845b",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    },
    {
      "label": "CONTACT",
      "sectionId": "contact",
      "pageHref": "contact.html",
      "sectionTitle": "contact",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#9e5757",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    }
  ]
};
