// Auto-generated by Homepage Configurator.
// Commit this file to keep draft settings synced across devices.
window.__CONFIGURATOR_DRAFT__ = {
  "brand": {
    "name": "VinATech",
    "logoSrc": "images/air2-logo-transparent-2.png",
    "logoFileName": "air2-logo-transparent-2.png",
    "logos": [
      {
        "src": "images/air2-logo-transparent-2.png",
        "fileName": "air2-logo-transparent-2.png",
        "x": 773,
        "y": 83,
        "size": 130,
        "rotation": 1,
        "transparency": 30
      },
      {
        "src": "images/vinatech-logo3-cut.png",
        "fileName": "vinatech-logo3-cut.png",
        "x": 198,
        "y": -86,
        "size": 500,
        "rotation": 0,
        "transparency": 40
      }
    ]
  },
  "hero": {
    "title": "Intelligence, Scale and Digital Solutions",
    "subtitle": "Inspire. Innovate. Ambition.",
    "titleFontFamily": "Sora",
    "subtitleFontFamily": "Manrope",
    "titleAlign": "center",
    "subtitleAlign": "center",
    "titleColor": "#f7fcfb",
    "subtitleColor": "#ebefee",
    "buttons": [
      {
        "label": "Solutions",
        "href": "solutions.html"
      },
      {
        "label": "Products",
        "href": "products.html"
      },
      {
        "label": "Support",
        "href": "support.html"
      },
      {
        "label": "Contact",
        "href": "contact.html"
      }
    ]
  },
  "theme": {
    "fontFamily": "Sora",
    "headingSize": 59,
    "bodySize": 20,
    "buttonTextSize": 16,
    "bgColor": "#52ad52",
    "textColor": "#dbe6e6",
    "accentColor": "#011919",
    "mutedColor": "#87a69e",
    "surfaceColor": "#987f67",
    "buttonTextColor": "#e0d1d1",
    "mobileHeadingSize": 59,
    "mobileBodySize": 20
  },
  "background": {
    "src": "images/nv-photo.png",
    "fileName": "",
    "transparency": 0,
    "x": 0,
    "y": 17
  },
  "layout": {
    "logo": {
      "x": 0,
      "y": 0
    },
    "nav": {
      "x": 1,
      "y": -42
    },
    "hero": {
      "x": 0,
      "y": 0
    },
    "heroTitle": {
      "x": 206,
      "y": 112
    },
    "heroSubtitle": {
      "x": 219,
      "y": 113
    },
    "cta": {
      "x": -91,
      "y": -362
    },
    "mobileNav": {
      "x": 0,
      "y": 0
    },
    "mobileHeroTitle": {
      "x": 0,
      "y": 0
    },
    "mobileHeroSubtitle": {
      "x": 0,
      "y": 0
    },
    "mobileCta": {
      "x": 0,
      "y": 0
    }
  },
  "display": {
    "pageMode": "home",
    "tabMode": "top-only",
    "topTabsTransparent": true,
    "ctaTextOnly": true,
    "previewPage": "home",
    "previewDevice": "desktop",
    "mobileHeroCenter": true,
    "mobileOverrides": true
  },
  "privacy": {
    "title": "Privacy Policy",
    "intro": "VINATECH Limited is committed to lawful, fair, and transparent handling of personal information. This policy explains what data we process, why we process it, and how we protect it.",
    "scopeText": "This policy applies to VINATECH Limited websites, digital services, and business communication channels. We process personal data only where it is relevant to providing our services, supporting customers, protecting security, or complying with legal obligations.",
    "dataText": "Depending on your interaction with us, we may process identity and contact details you submit, service-related communications and support records, and technical event logs required for security, fault analysis, and service continuity.",
    "noCookiesText": "VINATECH Limited does not use analytics cookies, marketing cookies, or social media tracking cookies on this website. We do not deploy cookie banners for profiling because no such cookies are collected.",
    "noMarketingText": "We do not build advertising profiles and we do not sell personal data to third parties. Where informational emails are required for active service relationships, they are limited to operational communications.",
    "howUseText": "To respond to enquiries and deliver requested services.\nTo provide support and maintain platform reliability.\nTo secure systems and investigate misuse or abuse.\nTo comply with regulatory, contractual, and legal duties.",
    "enforcementText": "VINATECH Limited applies a structured compliance model informed by public policy approaches from Google Play Developer Content Policy (privacy, deception prevention, responsible data handling, and clear user disclosures) and by data protection governance themes described by the Scottish Judiciary guidance on privacy and data protection.",
    "bgColor": "#f8fbfa",
    "textColor": "#18322b",
    "topTabsTransparent": false,
    "tabTextColor": "#18322b",
    "tabBgColor": "#ffffff",
    "mutedColor": "#5a736c",
    "lineColor": "#dce6e1",
    "accentColor": "#0f786b",
    "cardColor": "#ffffff",
    "topBandHeight": 76,
    "heroTopPadding": 50,
    "cardPadding": 26,
    "layoutGap": 26
  },
  "contact": {
    "title": "Contact VINATECH Limited",
    "intro": "Tell us about your project needs and our team will respond promptly.",
    "submitLabel": "Submit",
    "emailSubject": "Website Contact Request",
    "topTabsTransparent": false,
    "formEndpoint": "https://formspree.io/f/mrevdeyn",
    "recipientEmail": "support@vinatech.it.com",
    "fields": [
      {
        "id": "first-name",
        "label": "First Name",
        "type": "text",
        "required": true,
        "placeholder": "Your first name"
      },
      {
        "id": "last-name",
        "label": "Last Name",
        "type": "text",
        "required": true,
        "placeholder": "Your last name"
      },
      {
        "id": "business-email",
        "label": "Business Email",
        "type": "email",
        "required": true,
        "placeholder": "name@company.com"
      },
      {
        "id": "company",
        "label": "Company",
        "type": "text",
        "required": true,
        "placeholder": "Company name"
      },
      {
        "id": "message",
        "label": "Message",
        "type": "textarea",
        "required": true,
        "placeholder": "How can we help?"
      },
      {
        "id": "consent",
        "label": "I agree to the Privacy Policy",
        "type": "checkbox",
        "required": true,
        "placeholder": ""
      }
    ]
  },
  "tabs": [
    {
      "label": "HOME",
      "sectionId": "home",
      "pageHref": "index.html",
      "sectionTitle": "HOME",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#e5f0ea",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    },
    {
      "label": "NEWS",
      "sectionId": "news",
      "pageHref": "news.html",
      "sectionTitle": "NEWS",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#e5f0ea",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    },
    {
      "label": "PRIVACY POLICY",
      "sectionId": "privacy-policy",
      "pageHref": "privacy.html",
      "sectionTitle": "PRIVACY POLICY",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#e5f0ea",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    },
    {
      "label": "CONTACT",
      "sectionId": "contact",
      "pageHref": "contact.html",
      "sectionTitle": "CONTACT",
      "sectionText": "Add section content here.",
      "sectionFontFamily": "",
      "sectionTitleColor": "#102822",
      "sectionTextColor": "#4f6962",
      "sectionBackgroundColor": "#e5f0ea",
      "navFontFamily": "",
      "navTextColor": "#102822",
      "navBackgroundColor": "#e5f0ea",
      "sectionBackgroundSrc": "",
      "sectionBackgroundFileName": "",
      "sectionBackgroundTransparency": 36,
      "galleryLayout": "horizontal",
      "galleryImageTransparency": 0,
      "galleryImages": [
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        },
        {
          "src": "",
          "fileName": ""
        }
      ]
    }
  ]
};
