(function () {
  "use strict";

  function normalizeImageSrc(value) {
    return String(value || "").trim();
  }

  function ensureTwoLogos(brand) {
    var source = (brand && Array.isArray(brand.logos)) ? brand.logos.slice(0, 2) : [];
    while (source.length < 2) {
      source.push({ src: "" });
    }
    return source.map(function (logo) {
      return { src: normalizeImageSrc(logo && logo.src) };
    });
  }

  function buildRepoDraftScript(globalKey, draftState) {
    var key = String(globalKey || "__CONFIGURATOR_DRAFT__");
    return [
      "// Auto-generated by Homepage Configurator.",
      "// Commit this file to keep draft settings synced across devices.",
      "window." + key + " = " + JSON.stringify(draftState, null, 2) + ";",
      ""
    ].join("\n");
  }

  function getRepoDraftCandidate(globalObject, globalKey) {
    var root = globalObject || {};
    var key = String(globalKey || "__CONFIGURATOR_DRAFT__");
    var candidate = root[key];
    if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) {
      return null;
    }
    if (Object.keys(candidate).length === 0) {
      return null;
    }
    return candidate;
  }

  function shouldPreferRepoDraft(localCandidate, repoCandidate) {
    var localBrand = (localCandidate && localCandidate.brand) || {};
    var repoBrand = (repoCandidate && repoCandidate.brand) || {};

    var localLogos = ensureTwoLogos(localBrand);
    var repoLogos = ensureTwoLogos(repoBrand);

    var localLogoCount = localLogos.filter(function (logo) {
      return !!normalizeImageSrc(logo.src);
    }).length;
    var repoLogoCount = repoLogos.filter(function (logo) {
      return !!normalizeImageSrc(logo.src);
    }).length;

    if (repoLogoCount > localLogoCount) {
      return true;
    }

    var localTabs = Array.isArray(localCandidate && localCandidate.tabs) ? localCandidate.tabs : [];
    var repoTabs = Array.isArray(repoCandidate && repoCandidate.tabs) ? repoCandidate.tabs : [];
    if (repoTabs.length > localTabs.length) {
      return true;
    }

    var localLabels = localTabs.map(function (tab) {
      return String((tab && tab.label) || "").trim().toLowerCase();
    });
    var repoLabels = repoTabs.map(function (tab) {
      return String((tab && tab.label) || "").trim().toLowerCase();
    });
    var expectedNav = ["home", "news", "privacy policy", "contact"];
    var localNavScore = expectedNav.filter(function (label) {
      return localLabels.indexOf(label) >= 0;
    }).length;
    var repoNavScore = expectedNav.filter(function (label) {
      return repoLabels.indexOf(label) >= 0;
    }).length;

    return repoNavScore > localNavScore;
  }

  function resolveDraftSavePlan(hasRememberedDirectory, hasDirectoryPicker) {
    var remembered = !!hasRememberedDirectory;
    var picker = !!hasDirectoryPicker;

    if (remembered) {
      return {
        transport: "filesystem",
        shouldResolveDirectory: false
      };
    }

    if (picker) {
      return {
        transport: "filesystem",
        shouldResolveDirectory: true
      };
    }

    return {
      transport: "download",
      shouldResolveDirectory: false
    };
  }

  function classifyDraftSaveError(error) {
    var name = String(error && error.name || "");
    if (name === "AbortError") {
      return { kind: "abort" };
    }
    return { kind: "failure" };
  }

  function buildDraftSaveStatus(mode, repoDraftPath) {
    var path = String(repoDraftPath || "js/configurator.draft.js");
    if (mode === "filesystem-success") {
      return "Draft saved to " + path + ". Commit and push this file to reuse the same draft on another PC.";
    }
    if (mode === "download-success") {
      return "Draft downloaded as configurator.draft.js. Put it in js/ (overwrite existing) and commit.";
    }
    if (mode === "download-abort") {
      return "Folder selection canceled. Draft downloaded as configurator.draft.js instead.";
    }
    if (mode === "download-failure") {
      return "Direct folder save was unavailable. Draft downloaded as configurator.draft.js. Put it in js/ and commit.";
    }
    return "Draft operation completed.";
  }

  function buildDraftLoadStatus(mode, repoDraftPath) {
    var path = String(repoDraftPath || "js/configurator.draft.js");
    if (mode === "missing") {
      return "No repo draft found in " + path + ". Save one first.";
    }
    if (mode === "success") {
      return "Loaded draft from " + path + ".";
    }
    return "Draft load completed.";
  }

  function buildDraftImportStatus(success) {
    return success ? "Draft imported." : "Import failed: invalid JSON.";
  }

  window.ConfiguratorDraftBridge = {
    buildRepoDraftScript: buildRepoDraftScript,
    getRepoDraftCandidate: getRepoDraftCandidate,
    shouldPreferRepoDraft: shouldPreferRepoDraft,
    resolveDraftSavePlan: resolveDraftSavePlan,
    classifyDraftSaveError: classifyDraftSaveError,
    buildDraftSaveStatus: buildDraftSaveStatus,
    buildDraftLoadStatus: buildDraftLoadStatus,
    buildDraftImportStatus: buildDraftImportStatus
  };
})();
